name: 'Keep PRs up to date'
description: 'Merge default branch into open pull requests'
inputs:
  token:
    description: 'github token'
    required: true
    default: ''
  labels:
    description: 'only merge into PRs with this label. You cannot specify this value *and* the all option'
    required: false
  all:
    description: 'ignore labels and update all PRs.  You cannot specify this flag *and* set labels'
    required: false
    default: false
  default_branch:
    description: 'the branch that should get auto merged into PRs. e.g. development'
runs:
  using: 'node12'
  main: 'dist/index.js'
